spring.application.name=Credit4

spring.datasource.url=jdbc:sqlite:credit.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.thymeleaf.cache=false

server.error.whitelabel.enabled=false
telegram.bot.token=8555473914:AAE5VAwHzM40ZUrLPqOVD_pwPdgbmDuHfe4
telegram.bot.username=Credit4CalculatorBot
telegram.bot.enabled=true